server:
  port: 8088
spring:
  datasource:
    name: bbs
    url: jdbc:mysql://localhost:3306/comical_music?useSSL=false
    username: root
    password: 13072213550
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        enable_lazy_load_no_trans: true
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 100
    # password:
    database: 0
  #
  jackson:
    time-zone: GMT+8
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:SS
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
  mail:
    host: smtp.wxmpoi.xyz
    # mvc:
    #throw-exception-if-no-handler-found: true
    #static-path-pattern: /statics/**
    username: yourusername
    port: 25
    protocol: smtp
    password: yourpassword
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

aliyun:
  sms:
    accessKeyId: LTAI4Fc43JzfBGxDXf7qkb7N #创建的accesskey中的AccessKey ID
    accessKeySecret: bRGeZvuYtwYAdyzjBiFSWPXP6hTojn #创建的accesskey中的Access Key Secret
    template_code: SMS_189621502 #模板管理中的模板CODE
    sign_name: 滑稽音乐 #签名管理中的签名


